- name: deploy via ssh
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.FOREST_HOST }}
    username: ${{ secrets.FOREST_USER }}
    key: ${{ secrets.FOREST_KEY }}
    script: cd /root/forest/forest-api && git checkout master && git pull && npm i --no-progress && pm2 restart forest-api && exit 0